spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # allowMultiQueries=true : 다중 insert 허용
    url: jdbc:mysql://database-1.ckvcfoeqtntq.ap-northeast-2.rds.amazonaws.com:3306/asap?serverTimezone=Asia/Seoul&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: hyoreal000501
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_APP_PASSWORD} # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  type-aliases-package: asap.be.domain, asap.be.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    asap:
      be:
        repository: trace

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: asap-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
